from pynput.keyboard import Key

languages = [ 'en-US', 'de-DE' ]

replacements = {
    'equal': '=',
    'equals': '=',
    'equal spaced': ' = ',
    'dash': '-',
    'backtick': '`',
    'dollar sign': '$',
    'one': '1',
    'two': '2',
    'to': '2',
    'three': '3',
    'tree': '3',
    'free': '3',
    'for': '4',
    'four': '4',
    'five': '5',
    'six': '6',
    'seven': '7',
    'eight': '8',
    'nine': '9',
    'ten': '10',
    'eleven': '11',
    'twelve': '12',
    'thirteen': '13',
    'fourteen': '14',
    'fifteen': '15',
    'twenty': '20',
    'twentyfive': '25',
    'get pull': 'git pull',
    'get paul': 'git pull',
    'get push': 'git push',
    'get checkout': 'git checkout',
    'get branch': 'git branch',
    'get status': 'git status',
    'get log': 'git log',
    'git cherry pick': 'git cherry-pick ',
    'get cherry-pick': 'git cherry-pick ',
}

keys = {
    'enter': Key.enter,
    'center': Key.enter,
    'hunter': Key.enter,
    'wetter': Key.enter,
    'space': Key.space,
    'keyspace': Key.space,
    'backspace': Key.backspace,
    'delete': Key.delete,
    'arrow left': Key.left,
    'arrow right': Key.right,
    'arrow write': Key.right,
    'arrow up': Key.up,
    'arrow down': Key.down,
    'tab': Key.tab,
    'tabulator': Key.tab,
    'page up': Key.page_up,
    'page down': Key.page_down,
}